# Generated by Django 2.2.20 on 2021-04-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Example Model',
                'verbose_name_plural': 'Example Models',
            },
        ),
        migrations.CreateModel(
            name='ExampleNotUniqueForcedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Example not unique Model',
                'verbose_name_plural': 'Example not unique Models',
            },
        ),
        migrations.CreateModel(
            name='ExampleSlugifyNotForcedModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Example slugify not forced Model',
                'verbose_name_plural': 'Example slugify not forced Models',
            },
        ),
    ]
